//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnik
    {
        public Korisnik()
        {
            this.Narudzbina = new HashSet<Narudzbina>();
            this.Oglas = new HashSet<Oglas>();
        }
    
        public string IDKorisnik { get; set; }
        public string eMail { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Mesto { get; set; }
        public string Adresa { get; set; }
        public string Telefon { get; set; }
        public Nullable<int> Token { get; set; }
        public Nullable<int> MailStize { get; set; }
    
        public virtual ICollection<Narudzbina> Narudzbina { get; set; }
        public virtual ICollection<Oglas> Oglas { get; set; }
    }
}
