//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narudzbina
    {
        public int IDNarudzbina { get; set; }
        public string IDKorisnik { get; set; }
        public int IDOglas { get; set; }
        public string Status { get; set; }
        public System.DateTime Vreme { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Oglas Oglas { get; set; }
    }
}
