//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oglas
    {
        public Oglas()
        {
            this.Narudzbina = new HashSet<Narudzbina>();
        }
    
        public int IDOglas { get; set; }
        public string IDKorisnik { get; set; }
        public string Kategorija { get; set; }
        public string Naslov { get; set; }
        public string Opis { get; set; }
        public int Cena { get; set; }
        public int Kolicina { get; set; }
        public int Status { get; set; }
        public System.DateTime Datum { get; set; }
        public string LinkSlika { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual ICollection<Narudzbina> Narudzbina { get; set; }
    }
}
